In [2]:
import pandas as pd

In [3]:
inspections=pd.read_csv('Food_Inspections.csv')
licenses=pd.read_csv('Business_Licenses.csv')

C:\Users\Akshat Kansal\AppData\Local\Temp\ipykernel_1252\3647451707.py:2: DtypeWarning: Columns (0: ZIP CODE, 1: BUSINESS ACTIVITY ID, 2: BUSINESS ACTIVITY) have mixed types. Specify dtype option on import or set low_memory=False.
  licenses=pd.read_csv('Business_Licenses.csv')

In [4]:
inspections.head()

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,1068208,CHINA COURT RESTAURANT,CHINA COURT RESTAURANT,2141795.0,Restaurant,Risk 1 (High),1146 N MILWAUKEE AVE,CHICAGO,IL,60642.0,03/14/2012,License Re-Inspection,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.902462,-87.665306,"(41.902462266949634, -87.66530609467256)"
1,1072213,CUDDLE CARE,CUDDLE CARE,1622366.0,Daycare Above and Under 2 Years,Risk 1 (High),4800 S LAKE PARK AVE,CHICAGO,IL,60615.0,10/22/2012,Canvass,Pass,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,41.807922,-87.590693,"(41.80792179224785, -87.5906931090992)"
2,1072214,CUDDLE CARE,CUDDLE CARE,1622365.0,Daycare Above and Under 2 Years,Risk 1 (High),4800 S LAKE PARK AVE,CHICAGO,IL,60615.0,10/22/2012,Canvass,Pass,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,41.807922,-87.590693,"(41.80792179224785, -87.5906931090992)"
3,1072228,SHARKS FISH & CHICKEN,SHARKS FISH & CHICKEN,2069562.0,Restaurant,Risk 2 (Medium),101 E 51ST ST,CHICAGO,IL,60615.0,10/26/2012,Short Form Complaint,Pass,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",41.801892,-87.622566,"(41.80189221533366, -87.62256558837282)"
4,1072252,SALAAM RESTAURANT AND BAKERY,SALAAM RESTAURANT AND BAKERY,2141327.0,Restaurant,Risk 1 (High),700-706 W 79TH ST,CHICAGO,IL,60620.0,01/24/2013,Canvass,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,41.750787,-87.641667,"(41.750787498480555, -87.64166664542023)"

In [5]:
licenses.head()

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,...,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION
0,1330742-20260316,3066302,257556,1,D.M.N. CONSTRUCTION INC.,D.M.N. CONSTRUCTION INC.,8006 S NEVA AVE,BURBANK,IL,60459,...,03/16/2026,03/15/2028,03/27/2026,03/31/2026,AAI,NaN,NaN,NaN,NaN,NaN
1,2341550-20260216,3061505,18670,9,PETSMART LLC,"PETSMART, Inc. #2525",3736 N HALSTED ST 1,CHICAGO,IL,60613,...,02/16/2026,02/15/2028,01/12/2026,04/01/2026,AAI,NaN,18.0,41.950169,-87.649727,"(41.950168775392974, -87.64972683208136)"
2,2215670-20260316,3065851,51655,3,START EARLY,EARLY CHILDHOOD EDUCARE CENTER,5044 S WABASH AVE 1ST,CHICAGO,IL,60615,...,03/16/2026,03/15/2028,02/04/2026,03/31/2026,AAI,NaN,52.0,41.802458,-87.624433,"(41.8024577384093, -87.62443259498743)"
3,2492354-20260416,3071290,379187,1,SAFEWAY FOOD MARKET INC.,SAFEWAY FOOD MARKET INC.,4025 W ARMITAGE AVE 1,CHICAGO,IL,60639,...,04/16/2026,04/15/2027,03/31/2026,04/01/2026,AAI,NaN,NaN,41.917041,-87.727717,"(41.91704132709403, -87.72771694216716)"
4,2232512-20150316,2378333,378721,1,"LAKE PEAK, INC.",Bp,7600-7606 S HALSTED ST 1ST,CHICAGO,IL,60620,...,03/16/2015,03/15/2017,03/12/2015,03/13/2015,AAI,NaN,NaN,41.755996,-87.644328,"(41.7559957904814, -87.64432823886385)"

In [6]:
inspections_clean=inspections[(inspections['License #'].notnull()) & (inspections['Risk'].notnull()) & (inspections['License #']!=0) & (inspections['Risk']!='All')].copy()
print(f"Before : {len(inspections)}")
print(f"After : {len(inspections_clean)}")
print(f"Dropped : {len(inspections)-len(inspections_clean)}")

Before : 315158
After : 314177
Dropped : 981

In [7]:
inspections_clean['License #']=inspections_clean['License #'].astype(int)
inspections_clean['Inspection Date']=pd.to_datetime(inspections_clean['Inspection Date'],format='%m/%d/%Y')

In [8]:
inspections_clean.info()

<class 'pandas.DataFrame'>
Index: 314177 entries, 0 to 315157
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Inspection ID    314177 non-null  int64
 1   DBA Name         314177 non-null  str
 2   AKA Name         311841 non-null  str
 3   License #        314177 non-null  int64
 4   Facility Type    309002 non-null  str
 5   Risk             314177 non-null  str
 6   Address          314177 non-null  str
 7   City             313998 non-null  str
 8   State            314103 non-null  str
 9   Zip              314140 non-null  float64
 10  Inspection Date  314177 non-null  datetime64[us]
 11  Inspection Type  314176 non-null  str
 12  Results          314177 non-null  str
 13  Violations       225809 non-null  str
 14  Latitude         313143 non-null  float64
 15  Longitude        313143 non-null  float64
 16  Location         313143 non-null  str
dtypes: datetime64[us](1), float64(3), int64(2), str(11)
memory usage: 43.1 MB

In [9]:
licenses['LICENSE DESCRIPTION'].value_counts(dropna=False)

LICENSE DESCRIPTION
Limited Business License                         481904
Retail Food Establishment                        187484
Regulated Business License                        73456
Tobacco                                           58099
Consumption on Premises - Incidental Activity     41015
                                                  ...
Sports Facilities Authority License                   4
Outdoor Entertainment Venue                           3
Fast-Track Business Sign Registration                 2
Guard Dog Service                                     1
Airport Pushcart Liquor Midway - Class A              1
Name: count, Length: 150, dtype: int64

In [10]:
food_types = ['Retail Food Establishment', 'Wholesale Food Establishment', 'Special Event Food']
licenses_clean=licenses[licenses['LICENSE DESCRIPTION'].isin(food_types)].copy()

In [11]:
licenses_clean['LICENSE TERM START DATE']=pd.to_datetime(licenses_clean['LICENSE TERM START DATE'],format='%m/%d/%Y', errors='coerce')
licenses_clean=licenses_clean.sort_values('LICENSE TERM START DATE', ascending=False).copy()
licenses_clean=licenses_clean.drop_duplicates(subset='LICENSE NUMBER', keep='first').copy()
licenses_clean.shape

(60452, 37)

In [12]:
licenses_clean['LICENSE NUMBER']=pd.to_numeric(licenses_clean['LICENSE NUMBER'],errors='coerce')
licenses_clean=licenses_clean.dropna(subset='LICENSE NUMBER').copy()
licenses_clean['LICENSE NUMBER'] = licenses_clean['LICENSE NUMBER'].astype(int)

In [13]:
inspections_clean.head(10)

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,1068208,CHINA COURT RESTAURANT,CHINA COURT RESTAURANT,2141795,Restaurant,Risk 1 (High),1146 N MILWAUKEE AVE,CHICAGO,IL,60642.0,2012-03-14,License Re-Inspection,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.902462,-87.665306,"(41.902462266949634, -87.66530609467256)"
1,1072213,CUDDLE CARE,CUDDLE CARE,1622366,Daycare Above and Under 2 Years,Risk 1 (High),4800 S LAKE PARK AVE,CHICAGO,IL,60615.0,2012-10-22,Canvass,Pass,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,41.807922,-87.590693,"(41.80792179224785, -87.5906931090992)"
2,1072214,CUDDLE CARE,CUDDLE CARE,1622365,Daycare Above and Under 2 Years,Risk 1 (High),4800 S LAKE PARK AVE,CHICAGO,IL,60615.0,2012-10-22,Canvass,Pass,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,41.807922,-87.590693,"(41.80792179224785, -87.5906931090992)"
3,1072228,SHARKS FISH & CHICKEN,SHARKS FISH & CHICKEN,2069562,Restaurant,Risk 2 (Medium),101 E 51ST ST,CHICAGO,IL,60615.0,2012-10-26,Short Form Complaint,Pass,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",41.801892,-87.622566,"(41.80189221533366, -87.62256558837282)"
4,1072252,SALAAM RESTAURANT AND BAKERY,SALAAM RESTAURANT AND BAKERY,2141327,Restaurant,Risk 1 (High),700-706 W 79TH ST,CHICAGO,IL,60620.0,2013-01-24,Canvass,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,41.750787,-87.641667,"(41.750787498480555, -87.64166664542023)"
5,1072529,GRESHAM ELEMENTARY SCHOOL,GRESHAM ELEMENTARY SCHOOL,23451,School,Risk 1 (High),8524 S Green (832W),CHICAGO,IL,60620.0,2013-09-05,Canvass,Fail,12. HAND WASHING FACILITIES: WITH SOAP AND SAN...,41.738913,-87.645062,"(41.73891334027122, -87.6450616939937)"
6,2617821,MOVING EVEREST CHARTER SCHOOL,MOVING EVEREST CHARTER SCHOOL,3399494,School,Risk 1 (High),416 N LARAMIE,CHICAGO,IL,60644.0,2025-05-21,Canvass,Pass,16. FOOD-CONTACT SURFACES: CLEANED & SANITIZED...,41.888252,-87.755501,"(41.88825178615288, -87.75550107075298)"
7,2615511,MAPLEWOOD BREWING COMPANY,MAPLEWOOD BREWING COMPANY,3016105,Restaurant,Risk 1 (High),2717-2719 N MAPLEWOOD AVE,CHICAGO,IL,60647.0,2025-04-10,License,Pass,56. ADEQUATE VENTILATION & LIGHTING; DESIGNATE...,41.930957,-87.691376,"(41.93095692249829, -87.69137628601092)"
8,2615517,MAPLEWOOD BREWING COMPANY,MAPLEWOOD BREWING COMPANY,3016106,Restaurant,Risk 1 (High),2717-2719 N MAPLEWOOD AVE,CHICAGO,IL,60647.0,2025-04-10,License,Pass,NaN,41.930957,-87.691376,"(41.93095692249829, -87.69137628601092)"
9,1084236,THE JIBARITO STOP,THE JIBARITO STOP,2156722,Mobile Food Dispenser,Risk 3 (Low),2007-2009 S DAMEN AVE,CHICAGO,IL,60608.0,2012-05-25,License,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.854695,-87.675765,"(41.854694701707345, -87.67576513516751)"

In [14]:
violations=inspections_clean[['Inspection ID','Violations']].dropna(subset='Violations').copy()
violations['Violations']=violations['Violations'].str.split(r' \| ')
violations_long=violations.explode('Violations')
print(violations_long.shape)

(1018919, 2)

In [15]:
violations_long.head(10)

   Inspection ID                                         Violations
0        1068208  18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...
0        1068208  32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...
0        1068208  41. PREMISES MAINTAINED FREE OF LITTER, UNNECE...
1        1072213  31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...
1        1072213  32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...
1        1072213  35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...
1        1072213  41. PREMISES MAINTAINED FREE OF LITTER, UNNECE...
2        1072214  31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...
2        1072214  32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...
2        1072214  35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...

In [16]:
import re
extracted=violations_long['Violations'].str.extract(r'^(\d+)\.\s*(.*)')
violations_long['Violations_code']=extracted[0]
violations_long['Violations_text']=extracted[1]
print(violations_long['Violations_code'].isnull().sum())
violations_long.head(10)

0

,Inspection ID,Violations,Violations_code,Violations_text
0,1068208,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,18,NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS...
0,1068208,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,32,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...
0,1068208,"41. PREMISES MAINTAINED FREE OF LITTER, UNNECE...",41,"PREMISES MAINTAINED FREE OF LITTER, UNNECESSAR..."
1,1072213,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,31,CLEAN MULTI-USE UTENSILS AND SINGLE SERVICE AR...
1,1072213,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,32,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...
1,1072213,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...",35,"WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTE..."
1,1072213,"41. PREMISES MAINTAINED FREE OF LITTER, UNNECE...",41,"PREMISES MAINTAINED FREE OF LITTER, UNNECESSAR..."
2,1072214,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,31,CLEAN MULTI-USE UTENSILS AND SINGLE SERVICE AR...
2,1072214,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,32,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...
2,1072214,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...",35,"WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTE..."

In [17]:
licenses_clean = licenses_clean[[
    'LICENSE NUMBER', 'LEGAL NAME', 'DOING BUSINESS AS NAME',
    'WARD', 'ZIP CODE', 'LICENSE DESCRIPTION', 'LICENSE STATUS'
]].copy()
print(licenses_clean.shape)
licenses_clean.head()

(60452, 7)

,LICENSE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,WARD,ZIP CODE,LICENSE DESCRIPTION,LICENSE STATUS
19865,27935,LIAN'S INC,LIAN'S,49.0,60626,Retail Food Establishment,AAI
19460,2868609,BIG TIME FOOD & DELI INC.,BIG TIME FOOD & DELI,24.0,60624,Retail Food Establishment,AAI
20977,2867470,"PEPI COMPANY OF ILLINOIS, L.L.C.",ALONTI CATERING KITCHEN,34.0,60605,Retail Food Establishment,AAI
21019,2713090,"NEW EAT FIRST, INC.",EAT FIRST RESTAURANT,35.0,60618,Retail Food Establishment,AAI
21057,2492552,"PEPI COMPANY OF ILLINOIS, L.L.C.",ALONTI CATERING,12.0,60632,Retail Food Establishment,AAI

In [18]:
violations_long[['Violations_description','Violations_comment']]=violations_long['Violations_text'].str.split(' - Comments:',n=1,expand=True)
violations_long.head(10)

,Inspection ID,Violations,Violations_code,Violations_text,Violations_description,Violations_comment
0,1068208,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,18,NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS...,NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS...,"FOUND NO PEST CONTROL LOG BOOK ON PREMISES,FR..."
0,1068208,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,32,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...,SPLASHGUARD AT FRONT EXPOSED HANDSINK IS MISS...
0,1068208,"41. PREMISES MAINTAINED FREE OF LITTER, UNNECE...",41,"PREMISES MAINTAINED FREE OF LITTER, UNNECESSAR...","PREMISES MAINTAINED FREE OF LITTER, UNNECESSAR...","DETAIL CLEAN,ORGANIZE REAR STORAGE AREAS AND ..."
1,1072213,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,31,CLEAN MULTI-USE UTENSILS AND SINGLE SERVICE AR...,CLEAN MULTI-USE UTENSILS AND SINGLE SERVICE AR...,INVERT ALL MULTI-USE UTENSILS IN KITCHEN.
1,1072213,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,32,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...,REPAIR BROKEN CABINET DOORS/DRAWERS IN KITCH...
1,1072213,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...",35,"WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTE...","WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTE...",REPLACE ALL STAINED CEILING TILES IN KITCHEN ...
1,1072213,"41. PREMISES MAINTAINED FREE OF LITTER, UNNECE...",41,"PREMISES MAINTAINED FREE OF LITTER, UNNECESSAR...","PREMISES MAINTAINED FREE OF LITTER, UNNECESSAR...",REMOVE ALL UNNECESSARY CLUTTER IN NORTH HALLW...
2,1072214,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,31,CLEAN MULTI-USE UTENSILS AND SINGLE SERVICE AR...,CLEAN MULTI-USE UTENSILS AND SINGLE SERVICE AR...,INVERT ALL MULTI-USE UTENSILS IN KITCHEN.
2,1072214,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,32,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...,REPAIR BROKEN CABINET DOORS/DRAWERS IN KITCHEN.
2,1072214,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...",35,"WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTE...","WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTE...",REPLACE ALL STAINED CEILING TILES IN KITCHEN ...

In [19]:
violations_clean=violations_long[['Inspection ID', 'Violations_code', 'Violations_description', 'Violations_comment']].copy()
violations_clean['Violations_code']=violations_clean['Violations_code'].astype(int)
violations_clean['Violations_description']=violations_clean['Violations_description'].str.strip()
violations_clean['Violations_comment']=violations_clean['Violations_comment'].str.strip()

In [20]:
print(violations_clean.shape)
violations_clean.head()

(1018919, 4)

,Inspection ID,Violations_code,Violations_description,Violations_comment
0,1068208,18,NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS...,"FOUND NO PEST CONTROL LOG BOOK ON PREMISES,FRO..."
0,1068208,32,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...,SPLASHGUARD AT FRONT EXPOSED HANDSINK IS MISSI...
0,1068208,41,"PREMISES MAINTAINED FREE OF LITTER, UNNECESSAR...","DETAIL CLEAN,ORGANIZE REAR STORAGE AREAS AND R..."
1,1072213,31,CLEAN MULTI-USE UTENSILS AND SINGLE SERVICE AR...,INVERT ALL MULTI-USE UTENSILS IN KITCHEN.
1,1072213,32,FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DE...,REPAIR BROKEN CABINET DOORS/DRAWERS IN KITCHEN.

In [21]:
violations_clean['Violations_code'].value_counts().head(10)

Violations_code
55    84477
38    77261
34    71660
33    67449
35    65821
32    55281
41    40404
47    38969
36    35752
49    30613
Name: count, dtype: int64

In [22]:
merged=pd.merge(inspections_clean,licenses_clean, left_on='License #', right_on='LICENSE NUMBER', how='left',indicator=True)

In [23]:
print(merged['_merge'].value_counts())

_merge
both          259171
left_only      55006
right_only         0
Name: count, dtype: int64

In [24]:
licenses_clean.shape

(60452, 7)

In [25]:
violations_clean.shape

(1018919, 4)

In [26]:
import sqlite3

In [27]:
conn=sqlite3.connect('chicago_food_safety.db')

In [28]:
inspections_clean.to_sql('Inspections',conn,if_exists='replace',index=False)

314177

In [29]:
licenses_clean.to_sql('licenses', conn, if_exists='replace', index=False)
violations_clean.to_sql('violations', conn, if_exists='replace', index=False)

conn.close()
print("done")

done